import { PhysicsChapterMetadata } from './types';

/**
 * Registry of all 14 NCTB SSC Physics (পদার্থবিজ্ঞান) Chapters
 * Grounded directly against Supabase Subject: SSC-PHY (5c4d9443-cc92-4ab1-b602-b2caf9f79850)
 */
export const PHYSICS_CHAPTERS_REGISTRY: PhysicsChapterMetadata[] = [
  {
    id: 'beb7b083-912a-41cd-9814-8863c7902bb2',
    chapterNo: 1,
    subjectCode: 'SSC-PHY',
    titleEn: 'Physical World and Measurement',
    titleBn: 'ভৌত রাশি ও পরিমাপ',
    division: 'mechanics',
    divisionTitleEn: 'Mechanics & Measurement',
    divisionTitleBn: 'পরিমাপ ও মেকানিক্স',
    iconName: 'Gauge',
    estimatedMinutes: 20,
    boardMarksAllocation: 'ক/খ ও CQ অংশ (১-৪ নম্বর)',
    overviewEn: 'Understand fundamental and derived quantities, dimensions, vernier calipers, screw gauge, and measurement uncertainty.',
    overviewBn: 'মৌলিক ও লব্ধ রাশি, মাত্রা সমীকরণ, ভার্নিয়ার স্কেল, স্ক্রু গজ এবং পরিমাপের ত্রুটি নির্ভুলভাবে শেখো।',
    keyTopicsBn: ['ভার্নিয়ার ধ্রুবক (VC)', 'স্ক্রু গজের লঘিষ্ঠ গণন (LC)', 'মাত্রা সমীকরণ', 'আপেক্ষিক ত্রুটি'],
    keyTopicsEn: ['Vernier Constant (VC)', 'Least Count (LC)', 'Dimensional Analysis', 'Relative Error'],
    status: 'available',
  },
  {
    id: '03b4eda6-f98c-40e3-b77a-c2835515d9fa',
    chapterNo: 2,
    subjectCode: 'SSC-PHY',
    titleEn: 'Motion',
    titleBn: 'গতি',
    division: 'mechanics',
    divisionTitleEn: 'Mechanics & Measurement',
    divisionTitleBn: 'পরিমাপ ও মেকানিক্স',
    iconName: 'Activity',
    estimatedMinutes: 25,
    boardMarksAllocation: 'CQ ১০ নম্বর নিশ্চিত (বোর্ড প্রিয় অধ্যায়)',
    overviewEn: 'Master scalar and vector quantities, kinematics equations of uniform acceleration, velocity-time graphs, and freely falling bodies.',
    overviewBn: 'স্কেলার ও ভেক্টর, সুষম ত্বরণের ৪টি গতির সমীকরণ, বেগ-সময় লেখচিত্র এবং পরন্ত বস্তুর সূত্রাবলী।',
    keyTopicsBn: ['v = u + at', 's = ut + ½at²', 'v² = u² + 2as', 'বেগ-সময় লেখচিত্র', 'পড়ন্ত বস্তু'],
    keyTopicsEn: ['v = u + at', 's = ut + ½at²', 'v² = u² + 2as', 'v-t Graphs', 'Free Fall'],
    status: 'available',
  },
  {
    id: 'd09200a3-0cd8-48cf-ad6a-87518309c0e1',
    chapterNo: 3,
    subjectCode: 'SSC-PHY',
    titleEn: 'Force',
    titleBn: 'বল',
    division: 'mechanics',
    divisionTitleEn: 'Mechanics & Measurement',
    divisionTitleBn: 'পরিমাপ ও মেকানিক্স',
    iconName: 'Hammer',
    estimatedMinutes: 25,
    boardMarksAllocation: 'CQ ১০ নম্বর (নিউটনের ২য় সূত্র ও ভরবেগ)',
    overviewEn: 'Explore inertia, momentum, Newton’s laws of motion, conservation of momentum in collisions, and friction types.',
    overviewBn: 'জড়তা, ভরবেগ সংরক্ষণ সূত্র, নিউটনের ৩টি গতিসূত্র, সংঘর্ষের বেগ এবং ঘর্ষণ বলের হিসাব।',
    keyTopicsBn: ['F = ma', 'ভরবেগের সংরক্ষণ', 'সংঘর্ষ ও প্রত্যবর্তী বেগ', 'ঘর্ষণ বল ও সহগ'],
    keyTopicsEn: ['F = ma', 'Conservation of Momentum', 'Inelastic Collision', 'Frictional Force'],
    status: 'available',
  },
  {
    id: '8f240650-3511-4303-a517-70552b2d54ab',
    chapterNo: 4,
    subjectCode: 'SSC-PHY',
    titleEn: 'Work, Power and Energy',
    titleBn: 'কাজ, ক্ষমতা ও শক্তি',
    division: 'mechanics',
    divisionTitleEn: 'Mechanics & Measurement',
    divisionTitleBn: 'পরিমাপ ও মেকানিক্স',
    iconName: 'Zap',
    estimatedMinutes: 20,
    boardMarksAllocation: 'CQ ১০ নম্বর (কর্মদক্ষতা ও শক্তি সংরক্ষণ)',
    overviewEn: 'Work done by force, gravitational potential energy, kinetic energy, conservation of mechanical energy, and efficiency percentage.',
    overviewBn: 'কাজের সমীকরণ, গতিশক্তি ও বিভবশক্তি, যান্ত্রিক শক্তির সংরক্ষণশীলতা এবং ইঞ্জিনের কর্মদক্ষতা (η)।',
    keyTopicsBn: ['W = Fs cosθ', 'Ep = mgh & Ek = ½mv²', 'শক্তির সংরক্ষণশীলতা নীতি', 'কর্মদক্ষতা η (%)'],
    keyTopicsEn: ['W = Fs', 'Potential & Kinetic Energy', 'Conservation of Energy', 'Efficiency (η)'],
    status: 'available',
  },
  {
    id: '5a5043de-5b7b-4f64-8844-9b7ee2882ce5',
    chapterNo: 5,
    subjectCode: 'SSC-PHY',
    titleEn: 'State of Matter and Pressure',
    titleBn: 'পদার্থের অবস্থা ও চাপ',
    division: 'matter_thermal',
    divisionTitleEn: 'States of Matter & Heat',
    divisionTitleBn: 'পদার্থ ও তাপবিজ্ঞান',
    iconName: 'Droplets',
    estimatedMinutes: 25,
    boardMarksAllocation: 'CQ ১০ নম্বর (আর্কিমিডিস ও প্যাসকেল)',
    overviewEn: 'Density, pressure in liquids, Pascal’s law and hydraulic multiplier, Archimedes’ principle, buoyancy, and Hooke’s law of elasticity.',
    overviewBn: 'ঘনত্ব ও তরলের ভেতরের চাপ, প্যাসকেলের সূত্র ও হাইড্রোলিক প্রেস, আর্কিমিডিসের নীতি, প্লবতা এবং হুকের স্থিতিস্থাপক সূত্র।',
    keyTopicsBn: ['P = hρg', 'হাইড্রোলিক প্রেস (F₂/F₁ = A₂/A₁)', 'প্লবতা ও ভাসন-নিমজ্জন', 'ইয়ং-এর গুণাঙ্ক (Y)'],
    keyTopicsEn: ['P = hρg', 'Hydraulic Press', 'Buoyancy & Archimedes', "Young's Modulus"],
    status: 'available',
  },
  {
    id: '06c942d0-4993-4a5d-b6f9-81f36bb6d2bc',
    chapterNo: 6,
    subjectCode: 'SSC-PHY',
    titleEn: 'Effect of Heat on Matter',
    titleBn: 'বস্তুর উপর তাপের প্রভাব',
    division: 'matter_thermal',
    divisionTitleEn: 'States of Matter & Heat',
    divisionTitleBn: 'পদার্থ ও তাপবিজ্ঞান',
    iconName: 'Flame',
    estimatedMinutes: 20,
    boardMarksAllocation: 'CQ ১০ নম্বর (তাপধারণ ক্ষমতা ও প্রসারণ)',
    overviewEn: 'Thermal expansion of solids and liquids, temperature scales conversion, specific heat capacity, principle of calorimetry, and latent heat.',
    overviewBn: 'তাপমাত্রা স্কেল রূপান্তর, কঠিন ও তরলের তাপীয় প্রসারণ, আপেক্ষিক তাপ, ক্যালরিমিতির মূলনীতি এবং সুপ্ততাপ।',
    keyTopicsBn: ['তাপমাত্রা স্কেল রূপান্তর', 'দৈর্ঘ্য প্রসারণ সহগ (α, β, γ)', 'Q = msΔθ', 'গলনের সুপ্ততাপ'],
    keyTopicsEn: ['Temperature Scales', 'Thermal Expansion (α, β, γ)', 'Q = msΔθ', 'Latent Heat'],
    status: 'available',
  },
  {
    id: 'b433dc80-071a-472a-bec0-38d4fc2a9f88',
    chapterNo: 7,
    subjectCode: 'SSC-PHY',
    titleEn: 'Waves and Sound',
    titleBn: 'তরঙ্গ ও শব্দ',
    division: 'waves_optics',
    divisionTitleEn: 'Waves & Optics',
    divisionTitleBn: 'তরঙ্গ ও আলোকবিজ্ঞান',
    iconName: 'Waves',
    estimatedMinutes: 20,
    boardMarksAllocation: 'CQ ১০ নম্বর (প্রতিধ্বনি ও তরঙ্গ বেগ)',
    overviewEn: 'Transverse and longitudinal waves, amplitude, wavelength, wave equation v = fλ, speed of sound in air, and echo distance criteria.',
    overviewBn: 'অনুদৈর্ঘ্য ও অনুপ্রস্থ তরঙ্গ, তরঙ্গ সমীকরণ v = fλ, বায়ুতে শব্দের বেগ এবং প্রতিধ্বনি শোনার ন্যূনতম দূরত্বের হিসাব।',
    keyTopicsBn: ['v = fλ', 'শব্দোত্তর ও শব্দেতর তরঙ্গ', 'প্রতিধ্বনি ও ন্যূনতম দূরত্ব (16.6m)', 'শব্দের বেগের ওপর তাপমাত্রার প্রভাব'],
    keyTopicsEn: ['v = fλ', 'Echo Calculations', 'Audible Range (20Hz - 20kHz)', 'Temperature Effect on Sound'],
    status: 'available',
  },
  {
    id: 'c31c3c09-a302-48c4-a895-14ebbe388c58',
    chapterNo: 8,
    subjectCode: 'SSC-PHY',
    titleEn: 'Reflection of Light',
    titleBn: 'আলোর প্রতিফলন',
    division: 'waves_optics',
    divisionTitleEn: 'Waves & Optics',
    divisionTitleBn: 'তরঙ্গ ও আলোকবিজ্ঞান',
    iconName: 'Sun',
    estimatedMinutes: 25,
    boardMarksAllocation: 'CQ ১০ নম্বর (দর্পণ রশ্মিচিত্র ও বিবর্ধন)',
    overviewEn: 'Laws of reflection, plane mirrors, concave and convex spherical mirrors, focal length, ray tracing diagrams, and mirror equation.',
    overviewBn: 'প্রতিফলনের সূত্র, সমতল দর্পণ, অবতল ও উত্তল গোলীয় দর্পণে প্রতিবিম্ব গঠন, রশ্মিচিত্র অঙ্কন এবং বিবর্ধন (m = -v/u)।',
    keyTopicsBn: ['1/u + 1/v = 1/f', 'গোলীয় দর্পণে রশ্মিচিত্র', 'রৈখিক বিবর্ধন (m)', 'বাস্তব ও অবাস্তব প্রতিবিম্ব'],
    keyTopicsEn: ['Mirror Formula', 'Ray Tracing Diagrams', 'Linear Magnification (m)', 'Real vs Virtual Images'],
    status: 'available',
  },
  {
    id: 'efa6a79a-b26a-482d-ac94-226bcbb468cd',
    chapterNo: 9,
    subjectCode: 'SSC-PHY',
    titleEn: 'Refraction of Light',
    titleBn: 'আলোর প্রতিসরণ',
    division: 'waves_optics',
    divisionTitleEn: 'Waves & Optics',
    divisionTitleBn: 'তরঙ্গ ও আলোকবিজ্ঞান',
    iconName: 'Glasses',
    estimatedMinutes: 25,
    boardMarksAllocation: 'CQ ১০ নম্বর (স্নলের সূত্র ও লেন্স ক্ষমতা)',
    overviewEn: "Snell's law, refractive index, critical angle, total internal reflection, optical fibers, and convex/concave lens image formations.",
    overviewBn: 'প্রতিসরণাঙ্ক ও স্নেলের সূত্র, সংকট কোণ ও পূর্ণ অভ্যন্তরীণ প্রতিফলন, অপটিক্যাল ফাইবার এবং উত্তল ও অবতল লেন্সের ক্ষমতা (P = 1/f)।',
    keyTopicsBn: ["স্নেলের সূত্র (n₁ sin θ₁ = n₂ sin θ₂)", 'সংকট কোণ ও পূর্ণ অভ্যন্তরীণ প্রতিফলন', 'লেন্সের সমীকরণ ও ক্ষমতা (P)', 'চোখের ত্রুটি ও প্রতিকার'],
    keyTopicsEn: ["Snell's Law", 'Total Internal Reflection', 'Lens Power (P = 1/f)', 'Vision Defects & Correction'],
    status: 'available',
  },
  {
    id: '6a2c0280-5ca0-4f44-8ec6-11795b42b8bc',
    chapterNo: 10,
    subjectCode: 'SSC-PHY',
    titleEn: 'Static Electricity',
    titleBn: 'স্থির তড়িৎ',
    division: 'electricity_magnetism',
    divisionTitleEn: 'Electricity & Magnetism',
    divisionTitleBn: 'তড়িৎ ও চৌম্বকবিজ্ঞান',
    iconName: 'Atom',
    estimatedMinutes: 20,
    boardMarksAllocation: 'CQ ১০ নম্বর (কুলম্বের সূত্র ও তড়িৎ প্রাবল্য)',
    overviewEn: "Electrostatic induction, Coulomb's law, electric field intensity, electric potential, and capacitor charge storage.",
    overviewBn: 'তড়িৎ আবেশ, কুলম্বের সূত্রানুসারে আকর্ষণ-বিকর্ষণ বল, তড়িৎ ক্ষেত্র প্রাবল্য (E) এবং তড়িৎ বিভব (V) নির্ণয়।',
    keyTopicsBn: ["কুলম্বের সূত্র (F = k·q₁q₂/r²)", 'তড়িৎ প্রাবল্য E = F/q', 'তড়িৎ বিভব V = W/q', 'আধান বণ্টন ও আবেশ'],
    keyTopicsEn: ["Coulomb's Law", 'Electric Field Intensity', 'Electric Potential', 'Electrostatic Induction'],
    status: 'available',
  },
  {
    id: '2b769493-76bd-4a19-9ad5-587258809453',
    chapterNo: 11,
    subjectCode: 'SSC-PHY',
    titleEn: 'Current Electricity',
    titleBn: 'চল তড়িৎ',
    division: 'electricity_magnetism',
    divisionTitleEn: 'Electricity & Magnetism',
    divisionTitleBn: 'তড়িৎ ও চৌম্বকবিজ্ঞান',
    iconName: 'BatteryCharging',
    estimatedMinutes: 30,
    boardMarksAllocation: 'CQ ১০ নম্বর নিশ্চিত (বর্তনী ও বিল হিসাব)',
    overviewEn: "Ohm's law, factors of resistance, series and parallel circuit analysis, electromotive force, electrical power, and electricity billing (kWh).",
    overviewBn: 'ওহমের সূত্র, তুল্যরোধ (শ্রেণি ও সমান্তরাল), বিদ্যুৎ কোষের অভ্যন্তরীণ রোধ, বৈদ্যুতিক ক্ষমতা এবং ইউনিট/বিদ্যুৎ বিল হিসাব।',
    keyTopicsBn: ['ওহমের সূত্র (V = IR)', 'তুল্যরোধ হিসাব (Rs & Rp)', 'P = VI = I²R = V²/R', 'বিদ্যুৎ শক্তির হিসাব (kWh & Unit)'],
    keyTopicsEn: ["Ohm's Law", 'Equivalent Resistance', 'Electric Power (P)', 'Electrical Energy Billing'],
    status: 'available',
  },
  {
    id: '421c541e-75d0-4702-854c-b3710d207986',
    chapterNo: 12,
    subjectCode: 'SSC-PHY',
    titleEn: 'Magnetic Effect of Current',
    titleBn: 'বিদ্যুতের চৌম্বক ক্রিয়া',
    division: 'electricity_magnetism',
    divisionTitleEn: 'Electricity & Magnetism',
    divisionTitleBn: 'তড়িৎ ও চৌম্বকবিজ্ঞান',
    iconName: 'Compass',
    estimatedMinutes: 20,
    boardMarksAllocation: 'CQ/MCQ (সোলেনয়েড ও ট্রান্সফরমার)',
    overviewEn: 'Electromagnetism, solenoid field, motor principle, electromagnetic induction, generators, and step-up/step-down transformers.',
    overviewBn: 'বিদ্যুৎ প্রবাহের চৌম্বক ক্রিয়া, সোলেনয়েড, মোটরের ঘূর্ণন নীতি, তাড়িতচৌম্বক আবেশ এবং স্টেপ-আপ ও স্টেপ-ডাউন ট্রান্সফরমার।',
    keyTopicsBn: ['সোলেনয়েড ও তাড়িতচুম্বক', 'তাড়িতচৌম্বক আবেশ ও ফ্যারাডের সূত্র', 'ট্রান্সফরমার সমীকরণ (Ep/Es = Np/Ns)', 'মোটর ও জেনারেটর'],
    keyTopicsEn: ['Solenoid Field', 'Electromagnetic Induction', 'Transformer Equation', 'Electric Motor Principle'],
    status: 'available',
  },
  {
    id: '1034dddf-ca51-486f-a62d-e970f683a4cc',
    chapterNo: 13,
    subjectCode: 'SSC-PHY',
    titleEn: 'Modern Physics and Electronics',
    titleBn: 'আধুনিক পদার্থবিজ্ঞান ও ইলেকট্রনিক্স',
    division: 'modern_biomedical',
    divisionTitleEn: 'Modern Physics & Life',
    divisionTitleBn: 'আধুনিক বিজ্ঞান ও প্রযুক্তি',
    iconName: 'Sparkles',
    estimatedMinutes: 20,
    boardMarksAllocation: 'ক/খ ও MCQ অংশ',
    overviewEn: 'Radioactivity (alpha, beta, gamma rays), half-life, semiconductors (p-type & n-type), p-n junction diode, and modern telecommunication.',
    overviewBn: 'তেজস্ক্রিয়তা ও আলফা-বিটা-গামা রশ্মি, অর্ধায়ু, অর্ধপরিবাহী ডায়োড এবং আধুনিক তথ্য ও যোগাযোগ প্রযুক্তি।',
    keyTopicsBn: ['তেজস্ক্রিয় ক্ষয় ও অর্ধায়ু', 'p-টাইপ ও n-টাইপ সেমিকন্ডাক্টর', 'p-n জংশন ডায়োড ও রেকটিফায়ার', 'অ্যানালগ বনাম ডিজিটাল সিগন্যাল'],
    keyTopicsEn: ['Radioactivity & Half-life', 'Semiconductors (p & n)', 'p-n Junction Diode', 'Digital Electronics'],
    status: 'available',
  },
  {
    id: 'c32d2b59-d424-4d32-a086-ecab4a9b2f4b',
    chapterNo: 14,
    subjectCode: 'SSC-PHY',
    titleEn: 'Physics to Save Life',
    titleBn: 'জীবন বাঁচাতে পদার্থবিজ্ঞান',
    division: 'modern_biomedical',
    divisionTitleEn: 'Modern Physics & Life',
    divisionTitleBn: 'আধুনিক বিজ্ঞান ও প্রযুক্তি',
    iconName: 'Activity',
    estimatedMinutes: 15,
    boardMarksAllocation: 'ক/খ ও CQ প্রয়োগ অংশ',
    overviewEn: 'Biomedical physics instruments: X-ray, Ultrasonography, CT Scan, MRI, ECG, Endoscopy, and radiation safety precautions.',
    overviewBn: 'চিকিৎসাবিজ্ঞানে ব্যবহৃত পদার্থবিজ্ঞানের যন্ত্রপাতি: এক্স-রে, আল্ট্রাসনোগ্রাফি, সিটি স্ক্যান, এমআরআই, ইসিজি এবং বিকিরণ সতর্কতা।',
    keyTopicsBn: ['এক্স-রে ও সিটি স্ক্যান নীতি', 'এমআরআই (MRI) ও চৌম্বক অনুরণন', 'আল্ট্রাসনোগ্রাফি ও প্রতিধ্বনি', 'রেডিয়েশন ঝুঁকি ও নিরাপত্তা'],
    keyTopicsEn: ['X-ray & CT Scan Physics', 'MRI Technology', 'Ultrasonography', 'Radiation Safety'],
    status: 'available',
  },
];
